In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('wine_rev.csv', index_col=0)
data.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [4]:
sub_set = data[['country', 'points', 'price', 'winery']]

sub_set.head()

    country  points  price               winery
0     Italy      87    NaN              Nicosia
1  Portugal      87   15.0  Quinta dos Avidagos
2        US      87   14.0            Rainstorm
3        US      87   13.0           St. Julian
4        US      87   65.0         Sweet Cheeks

In [12]:
two = data.loc[:, ['country','province', 'points', 'price', 'winery']]

two.head(10)

    country           province  points  price               winery
0     Italy  Sicily & Sardinia      87    NaN              Nicosia
1  Portugal              Douro      87   15.0  Quinta dos Avidagos
2        US             Oregon      87   14.0            Rainstorm
3        US           Michigan      87   13.0           St. Julian
4        US             Oregon      87   65.0         Sweet Cheeks
5     Spain     Northern Spain      87   15.0               Tandem
6     Italy  Sicily & Sardinia      87   16.0      Terre di Giurfo
7    France             Alsace      87   24.0             Trimbach
8   Germany        Rheinhessen      87   12.0          Heinz Eifel
9    France             Alsace      87   27.0   Jean-Baptiste Adam

In [7]:
two[two.points >= 95]

          country  points   price                              winery
345     Australia     100   350.0         Chambers Rosewood Vineyards
346     Australia      98   350.0         Chambers Rosewood Vineyards
347       Germany      97   775.0                         Robert Weil
348     Australia      97   100.0         Chambers Rosewood Vineyards
349     Australia      97   225.0                            Torbreck
350         Italy      97   150.0                          Cavallotto
351       Hungary      96   320.0                              Oremus
352            US      96    68.0                            Rochioli
353        France      96   630.0                        Louis Latour
354       Germany      96   365.0                         Robert Weil
355            US      96    68.0                            Rochioli
356     Australia      95    85.0                         Jasper Hill
357        France      95   350.0                  Château de la Tour
358       Germany      95    66.0                 Weingut Hans Bausch
359        France      95   110.0                      Philippe Colin
360     Australia      95   125.0                            Torbreck
361         Italy      95    60.0                           Bel Colle
362            US      95   200.0                           J. Davies
363        France      95   380.0                        Louis Latour
364            US      95    48.0                           Winderlea
365     Australia      95    60.0                           Wakefield
1556           US      99   125.0                      Quilceda Creek
1557           US      99    94.0                     Williams Selyem
1558       France      98  1900.0                     Château Margaux
1559       France      98   380.0                      Château Palmer
1560           US      98    50.0                           Pirouette
1561        Italy      98   102.0                   Marchesi Antinori
1562       France      97   170.0             Château Troplong Mondot
1563        Italy      97   220.0                    Tenuta San Guido
1564        Italy      97   215.0               Tenuta dell'Ornellaia
...           ...     ...     ...                                 ...
126247         US      95    39.0                     Woodward Canyon
127368         US      98   100.0                           Goldeneye
127369         US      97   120.0                          Arkenstone
127370         US      97    75.0                           Goldeneye
127371    Germany      97   245.0  Geh. Rat Dr. von Bassermann-Jordan
127372         US      97   250.0                           Au Sommet
127373         US      96    75.0                           Goldeneye
127374    Germany      96   175.0                      St. Urbans-Hof
127572         US      97    54.0                       Merry Edwards
127573      Spain      97   180.0                         Emilio Moro
127574      Spain      96   204.0                         Emilio Moro
127575         US      96    70.0                     Kendall-Jackson
127576     France      96     NaN                     Château Guiraud
127577         US      95    40.0                              Failla
127578         US      95    70.0                      Freemark Abbey
127579         US      95    99.0                            Chehalem
127580         US      95   100.0                       Flora Springs
127581         US      95    85.0                                Piña
127582         US      95   125.0                             Barnett
128265         US      99   100.0                           Trefethen
128266    Germany      97   250.0                Dr. Pauly Bergweiler
128267         US      97    85.0                              Semper
128268         US      97    50.0                           Trefethen
128269         US      97   100.0                              Hestan
128270         US      97    65.0                              Redmon
128271      Spain      96    82.0                   Remírez de Ganuza
128681     France      95     NaN                               Deutz
128682         US      95    38.0                       Dutton Estate
128683         US      95    90.0                               Etude
128684         US      95   100.0                               Etude

[2416 rows x 4 columns]

In [15]:
two.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                                 country             province  points  price  \
country   province
Argentina Mendoza Province     Argentina     Mendoza Province      97  120.0
          Other                Argentina                Other      95   90.0
Armenia   Armenia                Armenia              Armenia      88   15.0
Australia Australia Other      Australia      Australia Other      93   15.0
          New South Wales      Australia      New South Wales      94   32.0
          South Australia      Australia      South Australia      99  850.0
          Tasmania             Australia             Tasmania      94   60.0
          Victoria             Australia             Victoria     100  350.0
          Western Australia    Australia    Western Australia      95   84.0
Austria   Austria                Austria              Austria      93    NaN
          Burgenland             Austria           Burgenland      98    NaN
          Carnuntum              Austria            Carnuntum      95   49.0
          Eisenberg              Austria            Eisenberg      95   55.0
          Kamptal                Austria              Kamptal      96   78.0
          Kremstal               Austria             Kremstal      96   70.0
          Leithaberg             Austria           Leithaberg      94  110.0
          Mittelburgenland       Austria     Mittelburgenland      92   27.0
          Neusiedlersee          Austria        Neusiedlersee      91    NaN
          Niederösterreich       Austria     Niederösterreich      96   45.0
          Steiermark             Austria           Steiermark      90   30.0
          Südburgenland          Austria        Südburgenland      95   79.0
          Südoststeiermark       Austria     Südoststeiermark      94   60.0
          Südsteiermark          Austria        Südsteiermark      94   40.0
          Thermenregion          Austria        Thermenregion      96   80.0
          Traisental             Austria           Traisental      94   70.0
          Vienna                 Austria               Vienna      94    NaN
          Wachau                 Austria               Wachau      96   56.0
          Wagram                 Austria               Wagram      96   50.0
          Wagram-Donauland       Austria     Wagram-Donauland      93   30.0
          Weinland Österreich    Austria  Weinland Österreich      92   36.0
...                                  ...                  ...     ...    ...
US        Hawaii                      US               Hawaii      87   28.0
          Idaho                       US                Idaho      91   20.0
          Illinois                    US             Illinois      86   26.0
          Iowa                        US                 Iowa      84   16.0
          Kentucky                    US             Kentucky      83   35.0
          Massachusetts               US        Massachusetts      89   25.0
          Michigan                    US             Michigan      91   28.0
          Missouri                    US             Missouri      86   21.0
          Nevada                      US               Nevada      85   22.0
          New Jersey                  US           New Jersey      87   35.0
          New Mexico                  US           New Mexico      88   20.0
          New York                    US             New York      94   39.0
          North Carolina              US       North Carolina      90   18.0
          Ohio                        US                 Ohio      87   11.0
          Oregon                      US               Oregon      99   75.0
          Pennsylvania                US         Pennsylvania      91   33.0
          Rhode Island                US         Rhode Island      90   25.0
          Texas                       US                Texas      89   35.0
          Vermont                     US              Vermont      85   45.0
          Virginia                    US             Virginia      92   35.0
          Washington                  US           Washington     100   80.0
          Washington-Oregon           US    Washington-Oregon      90   30.0
Ukraine   Ukraine                Ukraine              Ukraine      88    9.0
Uruguay   Atlantida              Uruguay            Atlantida      88   21.0
          Canelones              Uruguay            Canelones      92   43.0
          Juanico                Uruguay              Juanico      90   45.0
          Montevideo             Uruguay           Montevideo      91   60.0
          Progreso               Uruguay             Progreso      90   46.0
          San Jose               Uruguay             San Jose      87   50.0
          Uruguay                Uruguay              Uruguay      91   22.0

                                                    winery
country   province
Argentina Mendoza Province            Bodega Catena Zapata
          Other                                     Colomé
Armenia   Armenia                                 Van Ardi
Australia Australia Other                  Marquis Philips
          New South Wales                       De Bortoli
          South Australia                         Penfolds
          Tasmania                               Tolpuddle
          Victoria             Chambers Rosewood Vineyards
          Western Australia                      Moss Wood
Austria   Austria                                  Kracher
          Burgenland                               Kracher
          Carnuntum                  Muhr-Van der Niepoort
          Eisenberg                                 Jalits
          Kamptal                              Bründlmayer
          Kremstal                                   Malat
          Leithaberg                               Prieler
          Mittelburgenland                        Heinrich
          Neusiedlersee                              Heiss
          Niederösterreich              Schloss Gobelsburg
          Steiermark                                 Skoff
          Südburgenland                           Krutzler
          Südoststeiermark                      Neumeister
          Südsteiermark                           Wohlmuth
          Thermenregion               Johanneshof Reinisch
          Traisental                          Markus Huber
          Vienna                      Stift Klosterneuburg
          Wachau                            Emmerich Knoll
          Wagram                               Anton Bauer
          Wagram-Donauland                     Anton Bauer
          Weinland Österreich                      Weszeli
...                                                    ...
US        Hawaii                                Ulupalakua
          Idaho                           Koenig Vineyards
          Illinois                  Illinois Sparkling Co.
          Iowa                                      Jasper
          Kentucky                     Elk Creek Vineyards
          Massachusetts                        Still River
          Michigan                                Bel Lago
          Missouri                   Mount Pleasant Winery
          Nevada                              Nevada Ridge
          New Jersey                              Heritage
          New Mexico                          La Chiripada
          New York                       Hermann J. Wiemer
          North Carolina                        Raffaldini
          Ohio                                     Debonné
          Oregon                                    Cayuse
          Pennsylvania                          Chaddsford
          Rhode Island                            Sakonnet
          Texas                             Llano Estacado
          Vermont                                Snow Farm
          Virginia                             King Family
          Washington                         Charles Smith
          Washington-Oregon                     Ken Wright
Ukraine   Ukraine                                  Koblevo
Uruguay   Atlantida                           Bracco Bosca
          Canelones                                  Bouza
          Juanico                           Familia Deicas
          Montevideo                                 Bouza
          Progreso                                  Pisano
          San Jose                          Castillo Viejo
          Uruguay                                  Narbona

[425 rows x 5 columns]